\echo # Creating profiles view
set search_path = api, public;
create or replace view profiles as
select 
    
    id as id,
    name,
    self_summary,
    gender,
    gender_type,
    relationship_status,
    speaks,
    dob,
    display_picture,
    album,
    educational_stage,
    educational_modifier,
    is_student,
    diet,
    body_type,
    smokes,
    drinks,
    uses_drugs,
    zodiac,
    zodiac_attitude,
    children,
    wants_children,
    has_dog,
    has_cat,
    height_in_cm,
    what_do_i_do,
    i_am_good_at,
    people_first_notice,
    fave_books,
    fave_movies,
    fave_shows,
    fave_music,
    fave_food,
    fave_blogs,
    fave_comics,
    fave_research_papers,
    what_do_i_think_about,
    ideal_use_of_freetime,
    things_cant_do_without,
    most_private_shareables,
    message_me_if,
    orientation,
    show_me_to_non_straight_only,
    search_intention,
    search_radius_in_km,
    search_age_range_lowest,
    search_age_range_highest,
    search_genders,
    search_single_only,
    search_only_non_monogamous,
    country_iso,
    city_id
from data.profile t;
alter view profiles owner to api; -- it is important to set the correct owner to the RLS policy kicks in
